repos:
- repo: local
  hooks:
    - id: unit-tests
      name: unit tests
      entry: mvn clean test
      language: system
      pass_filenames: false

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
