repos:
- repo: https://github.com/ejba/pre-commit-maven
  rev: v0.3.4
  hooks:
    - id: maven-test
    - id: maven-compile

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
